### ISSUE TITLE
Cannot get accurate render of project pages on Github

### ISSUE THREAD

**Issue by GrantPax** [github/pages-gem#114]
As best I can tell, I have followed the jekyll config to the letter. I've used the [Gemfile from jekyll](http://jekyllrb.com/docs/github-pages/) which reads the json Github requirements. I've added nothing. Only content is what is produced by `jekyll new`. Here's what we get (below). Any ideas?

![screen shot 2015-01-17 at 11 16 16 pm](https://cloud.githubusercontent.com/assets/5502828/5791407/582ce56e-9ea2-11e4-9e70-f821f6413fb9.png)
![screen shot 2015-01-17 at 11 16 34 pm](https://cloud.githubusercontent.com/assets/5502828/5791406/5829c820-9ea2-11e4-8e7d-d8b00c13dcb4.png)

**Comment by GrantPax** [comment]
Here's the [repo](https://github.com/GrantPax/osgi.enroute.site.gh-pages) if you are at all interested.

**Comment by gjtorikian** [comment]
If you check out the developer console in the browser, there are a couple of images around CSS:

![screen shot 2015-01-17 at 8 49 16 pm](https://cloud.githubusercontent.com/assets/64050/5791430/5cd5b36a-9e8a-11e4-8c2d-2f44ab14a7a1.png)

I don't see *main.css* in your Pages repo: https://github.com/GrantPax/osgi.enroute.site/tree/gh-pages/css, so that might be it.

**Comment by gjtorikian** [comment]
There's an extra slash in your `head` tag:

![screen shot 2015-01-17 at 8 51 22 pm](https://cloud.githubusercontent.com/assets/64050/5791431/a2a5824e-9e8a-11e4-9780-f11fa7eb9216.png)

**Comment by djacquel** [comment]
In _config.yml : baseurl: /repositoryname

**Comment by GrantPax** [comment]
Thanks. It must be the Jekyll gen stuff. As I said, I did no coding. I wonder why the local run of Jekyll didn't barf.
