### ISSUE TITLE
Pages served only under URLs like PageName.html, not as PageName

### ISSUE THREAD

**Issue by peter-kehl** [github/pages-gem#135]
I have an organization GitHub page (repo: https://github.com/selite/selite.github.io), which contains .md files. When accessing it on GitHub at http://selite.github.io, it serves all .md files that have YAML Front matter (i.e. all .md files, except for TableOfContents.md) well, under URLs either without an extension or with .html extension. E.g. SeleniumIDE.md can be accessed as http://selite.github.io/SeleniumIDE or http://selite.github.io/SeleniumIDE.html.

However, when I run it locally via Jekyll as per https://help.github.com/articles/using-jekyll-with-pages/#troubleshooting, the files only work under .html URLs - e.g. http://localhost:4000/SeleniumIDE.html.

Is this a bug or am I doing something wrong? If a bug, is it the same as https://github.com/github/pages-gem/issues/69?

I have ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-linux] and (I believe) current gems. My Gemfile is:
source 'https://rubygems.org'
gem 'github-pages'
#gem "therubyracer"
#gem 'thin'

**Comment by spraints** [comment]
This is a difference in configuration between our server and the server jekyll runs. Jekyll 3.0 will include https://github.com/jekyll/jekyll/pull/3452, which fixes this.

#69 is different... In that issue, links to `index.md` in markdown work on github.com because the file is called `index.md`. On a pages site, the file is rendered and renamed to `index.html`, so the `index.md` link breaks.
