### ISSUE TITLE
Adding themes

### ISSUE THREAD

**Issue by ggarnier** [github/pages-gem#164]
Is it possible to use a different theme with this gem? I searched for themes in http://jekyllthemes.org/, but usually the installation is through forking the theme project on github. How can I do that with `github-pages` gem?

**Comment by Stargator** [comment]
The gem doesn't define the theme. The themes are generally defined through the css or sass files that the files in the folders _layouts and/or _includes.

For example, I merged in the differences between one blog theme with my site. It takes a bit of HTML understanding, but it's just a matter of merging in what you want and leaving out the rest.

It usually means some trial and error since not all themes are developed to make the process easy.

**Comment by ggarnier** [comment]
I see, but the problem is, if I want to use a different theme (like https://github.com/diezcami/arctic-fox-theme/), I would have to manually merge the differences between what's generated by `github-pages` gem and what's defined in the theme repository. Is there an easier way to do this?

**Comment by Stargator** [comment]
I customized the config.yaml and I removed any unwanted css/sass files. And modified the layout html as I desired. I did all of that before I ran jekyll build to have github-pages to generate the website.

Looking at the example theme you are point to, there is nothing in the config.yaml file to control the theme. Focus on the _includes, _layouts, _sass, css, index.html, and about.md and you should be good.

The way that author is using that site. He takes the contents of https://github.com/diezcami/arctic-fox-theme/ and places in a folder for a normal jekyll website. All the theme's repo is missing is a Gemfile containing the lines telling it to pull down github-pages.

So what you need to do, is fork the theme and ensure it has a Gemfile that contains ___at a minimal___:

```ruby
source 'https://rubygems.org'
gem 'github-pages
```

Since the theme doesn't include a Gemfile than it doesn't seem to be dependent on any particular ruby code.

**Comment by ggarnier** [comment]
@Stargator I just did that for [qck theme](https://github.com/qckanemoto/jekyll-qck-theme), it's working perfectly. Thanks!
