### ISSUE TITLE
Include Jekyll-scholar?

### ISSUE THREAD

**Issue by i2000s** [github/pages-gem#207]
Hi there,

Seems Jekyll-scholar is not supported in github-pages. Could you consider to add this plugin? Thanks.

Qi

**Comment by DirtyF** [comment]
@i2000s Github-pages don't support all Jekyll plugins, mainly for security reasons. And I don't think it's gonna change anytime soon.

The good news is that you can still build your site locally and upload it in order to use the plugins you need. You will find many ways to do it the hacker way, like for instance launching this ruby task before pushing : http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html

**Comment by i2000s** [comment]
Thanks for clarifying and the helpful link. Feel free to close this
issue due to my ignorance.
