### ISSUE TITLE
Suggested  bundler usage?

### ISSUE THREAD

**Issue by yuloh** [github/pages-gem#261]
Hello,

I am planning on setting up my Gemfile like [Jekyll suggests](https://jekyllrb.com/docs/github-pages/) and not committing the Gemfile.lock:

```ruby
source 'https://rubygems.org'

require 'json'
require 'open-uri'
versions = JSON.parse(open('https://pages.github.com/versions.json').read)

gem 'github-pages', versions['github-pages'], group: :jekyll_plugins
```

The idea being that the locally installed version of the gem is always in sync with github pages, and I won't need to run bundle update all of the time.

I am also using the group: `:jekyll_plugins` so that the github pages configuration is loaded.

Since the readme suggests simply doing `gem 'github-pages', group: :jekyll_plugins` and running `bundle update` to stay up to date, I was wondering if there are any downsides to using the `versions.json` approach?

**Comment by benbalter** [comment]
The method described in the Jekyll documentation will make an HTTP call every time you run `bundle`, meaning, it won't work if you don't have internet access (even if the Gems are cached locally). I'm also not sure when the `Gemfile` is processed, so you may occasionally get an opaque error that a Gem was not found (the solution being running `bundle update`), because the Gems listed remotely changed.

**Comment by yuloh** [comment]
Wow, I didn't realize it made the HTTP call every time you ran bundle.  `bundle exec jekyll serve`  doesn't even work without internet.

Thanks for the clarification!
