### ISSUE TITLE
Proposal: Html minfier

### ISSUE THREAD

**Issue by rogervila** [github/pages-gem#393]
### Before submitting an issue, please be sure to

- [X] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [X] Update to the latest Gem version (either `gem update github-pages` or `bundle update github-pages`)

### This issue affects

- [X] The site generated by GitHub Pages
- [ ] Building sites locally

Hello,

I already sent my request via GitHub support, as the contributing instructions said, but I'm posting it here too in order to discuss it with other devs.

Since Github pages are static, it would be nice to add support for a html minifier plugin.
The **2 main benefits** are:
- Increases the speed by reducing the request size
- Saves tons of data to the GitHub servers

In my jekyll sites I use this plugin: https://github.com/octopress/minify-html

What do you think?

**Comment by benbalter** [comment]
> I already sent my request via GitHub support, as the contributing instructions said

@rogervila thanks for submitting your request via GitHub Support. As I'm cleaning up the issue backlog, I'm going to close this issue since your request is being tracked there. 

To note, GitHub Pages sites are gzip'd prior to serving, which should reduce the payload size to a similar degree, including non-whitespace characters.
