### ISSUE TITLE
Change of theme ends up with Jekyll error

### ISSUE THREAD

**Issue by ssierral** [github/pages-gem#416]
### Before submitting an issue, please be sure to

- [X] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [X] Update to the latest Gem version (either `gem update github-pages` or `bundle update github-pages`)

### This issue affects

- [X] The site generated by GitHub Pages
- [X] Building sites locally

### What did you do (e.g., steps to reproduce)
I created a pages site and tried to change theme from minima to jekyll-theme-dinky. And then ran the usual steps.

- Modified _config.yml for using `theme: jekyll-theme-dinky`
- Executed `bundle install`
- `bundle update github-pages`
- `bundle exec jekyll serve`

As it did not work I tried to modify it online at github with the settings tool for automatically changing the theme of the site.
### What did you expect to happen?
Github page to work as usual with the modified theme.
### What happened instead?
For my local site I got the following error:
```
     Build Warning: Layout 'post' requested in _posts/2017-02-05-welcome-to-jekyll.markdown does not exist. 
  Liquid Exception: no implicit conversion of nil into String in about.md  
jekyll 3.3.1 | Error:  no implicit conversion of nil into String
```

For the github-pages automatic theme changer I got only:
```
The page build failed with the following error:   
Page build failed.
```
### Additional information
I did some research and found out that this was fixed for jekyll 3.4.0, and was generated by issue [Jekyll issue number 5750](https://github.com/jekyll/jekyll/pull/5750). However Github-pages has dependencies on Jekyll 3.3.1 and I could not force the local site to be build at least on 3.4.0.

* Link to the live site (if applicable):
* Link to the source repo (if applicable): [Repo](https://github.com/ssierral/ssierral.github.io)

**Comment by ashmaroli** [comment]
Removing the two `{% include -- %}` inside `about.md` should help you switch themes easily.

**Comment by OneGneissGuy** [comment]
Has this issue been resolved?
I am experiencing the same issue as @ssierral and have followed the same steps to change the them as, but I do not have any {% include -- %} to remove as suggested by @ashmaroli.
I am using Jekyll 3.4.0 on Ubuntu 16.04

**Comment by ashmaroli** [comment]
@OneGneissGuy I've updated my earlier comment for clarity. You need to remove the references to includes `{% include icon-github.html username="jekyll" %}` within `about.md` to unlink from `minima`. If you do not have this line in your `about.md`, what does the error message say otherwise, at GitHub and locally?

**Comment by OneGneissGuy** [comment]
Locally when I run :
`bundle exec jekyll serve --watch
` 
I get the following:
```
Build Warning: Layout 'post' requested in _posts/2017-05-07-welcome-to-jekyll.markdown does not exist. 
Build Warning: Layout 'page' requested in about.md does not exist. 
Build Warning: Layout 'home' requested in index.md does not exist. 
```

**Comment by OneGneissGuy** [comment]
When I change the theme, I get a blank page at my url in github pages

**Comment by ashmaroli** [comment]
The issue seems to be with one of the plugins used by GitHub Pages. For now, if you want to switch to any other theme supported on GitHub Pages, simply add a `_layouts` directory to your site's root with following files:

`_layouts/pages.html`
```
---
layout: default
---
{{ content }}
```
`_layouts/posts.html`
```
---
layout: default
---
{{ content }}
```
**Note: You need to remove this directory if you ever decide on using default Minima again**

**Comment by OneGneissGuy** [comment]
Hi,
I've added these files and updated _config.yml to enable the jekyll-theme-midnight but I still encounter the same issue as before- the site comes up blank.

**Comment by ashmaroli** [comment]
@OneGneissGuy I forked your site and applied above workaround. Check this temporary [link](https://ashmaroli.github.io/onegneissguy/about/)

**Comment by harrisnguyen94** [comment]
@ssierral @OneGneissGuy Hi, I noticed that this issue is still open. I came across the same problem the other days. Aside from the implicit conversion bug, which has now been fixed (the latest pages gem now has jekyll 3.4.5 as dependencies), the build process fails because other supported themes for github pages only have the 'default' layout. _Change all layout declared in Front Matter to 'default'_, or _build the missing layouts_ yourself and you would be good to go.
(In case you don't know how to modify the gem-based theme, please check Jekyll's documentation: https://jekyllrb.com/docs/themes/)

**Comment by bezoris** [comment]
For anyone still running in to this issue, this error occurs because of different frontmatter naming schemes as defined in different themes...

For instance, when setting up a new site you use the sample 'new post' from jekyllrb.com/docs/posts/
```
---  
layout: post  
title:  "Welcome to Jekyll!"  
date:   2015-11-17 16:16:01 -0600  
categories: jekyll update  
---
```
If you decide to apply, say, the 'Minimal Mistakes' theme (https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/), this error will pop up on build.

This happens because your sample frontmatter is requesting the 'post' layout, which does not exist in this particular theme. A quick look at the Minimal structure tab --
```
├── _layouts
|  ├── archive-taxonomy.html   # tag/category archive for Jekyll Archives plugin
|  ├── archive.html            # archive tlisting documents in an array
|  ├── compress.html           # compresses HTML in pure Liquid
|  ├── default.html            # base for all other layouts
|  ├── home.html               # home page
|  ├── single.html             # single document (post/page/etc)    <<<
|  └── splash.html             # splash page
```
-- shows us that in this particular theme we need to specify the 'single' layout for posts, not 'post'.

Making this change to our post frontmatter resolves the issue and allows us build without error:
```
---
layout: single    <<<
title:  "Welcome to Jekyll!"
date:   2015-11-17 16:16:01 -0600
categories: jekyll update
---
```
The takeaway is: remember that naming conventions are not uniform. This is one of the great things about Jekyll--that pretty much anything is editable--but it also means that things like this happen when we stray from convention.

Best, Chris

**Comment by NormBirkett** [comment]
I'm trying to use the gem theme jekyll-theme-merlot. I've added it to my gemfile.

I've tried both of the changes described above -- added the _layouts folder with the two files specified, and changed "layout: post" to "layout: default" in the sample post generated for me, but I'm still getting an error when I build.

![image](https://user-images.githubusercontent.com/42503567/46326273-01db1200-c5ca-11e8-83ec-0e55f80a41cf.png)

I used "default" in place of "post" because, as far as I can tell, it is the only layout in this theme:

![image](https://user-images.githubusercontent.com/42503567/46326299-1cad8680-c5ca-11e8-8dec-4987af2221ee.png)

Can anyone suggest what I might be doing wrong?

Norm

**Comment by Atcold** [comment]
Solution: substitute `post`, `page`, and `home` with `default`. That's it.

**Comment by rohitdavas** [comment]
> For anyone running in to this issue under different circumstances, this error can also occur because of unconventional frontmatter naming schemes across different themes.
> 
> For instance, when setting up a new site let's say you use the sample post from `jekyllrb.com/docs/posts/`
> 
> ```
> ---  
> layout: post  
> title:  "Welcome to Jekyll!"  
> date:   2015-11-17 16:16:01 -0600  
> categories: jekyll update  
> ---
> ```
> 
> If you decide to apply, say, the 'Minimal Mistakes' theme (https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/), this error will pop up on build.
> 
> This happens because your build is requesting the 'post' layout as defined in the sample frontmatter, which does not exist in this particular theme. A quick look at the Minimal structure tab --
> 
> ```
> ├── _layouts
> |  ├── archive-taxonomy.html   # tag/category archive for Jekyll Archives plugin
> |  ├── archive.html            # archive tlisting documents in an array
> |  ├── compress.html           # compresses HTML in pure Liquid
> |  ├── default.html            # base for all other layouts
> |  ├── home.html               # home page
> |  ├── single.html             # single document (post/page/etc)    <<<
> |  └── splash.html             # splash page
> ```
> 
> -- shows us that in this particular theme we need to specify the 'single' layout for posts, not 'post'.
> 
> Making this change to our post frontmatter resolves the issue and allows us to build without error.
> 
> ```
> ---
> layout: single    <<<
> title:  "Welcome to Jekyll!"
> date:   2015-11-17 16:16:01 -0600
> categories: jekyll update
> ---
> ```
> 
> The takeaway is: remember that naming conventions are not uniform. This is one of the great things about Jekyll--that pretty much anything is editable--but it also means that things like this happen when we stray from convention in our customizations.
> 
> Best, Chris

This is the exct reason. 
Thanks. It's working now.

**Comment by parkr** [comment]
This looks like an upstream issue with Jekyll where a layout doesn’t exist.

The old behavior is that it would ignore the layout and return whatever it has with a warning to the user in the terminal.

This new behavior with some “cryptic” `nil` message looks like a bug. Please feel free to start a conversation with the Jekyll folks. 😄

**Comment by ehsong** [comment]
Hi! I'm having trouble building the website as well, I have all the layout files in the _layout folder, but I am getting errors like this:

```
Build Warning: Layout 'single' requested in pages/about.md does not exist.
     Build Warning: Layout 'archive' requested in pages/dissertation.md does not exist.
     Build Warning: Layout 'archive' requested in pages/research.md does not exist.
     Build Warning: Layout 'archive' requested in pages/software does not exist.
     Build Warning: Layout 'archive' requested in pages/teaching.md does not exist.
```

I can't make sense of this, because I have single.html and archive.html all in the _layout folder.

**Comment by sylhare** [comment]
It looks like this stack over flow question [Can't get my gem based theme to work. Theme can't find layouts](https://stackoverflow.com/a/59794020/7747942).

**Comment by geostrophic** [comment]
perhaps you should try to change or delete files containing 'layout' or change a theme

**Comment by Iotaslair** [comment]
For the future just in case anyone did the same thing as me. Make sure that your folder name is _layouts not _layout. I spent roughly 2 hours combing the internet and testing only to find out I was missing an s at the end of the folder name

**Comment by LoneWolf4713** [comment]
I used another theme , but downloading the entire theme from github and putting it in my folder worked .
But be sure NOT to replace any files. just copy , which are getting copied .
