### ISSUE TITLE
update to Jekyll 3.8

### ISSUE THREAD

**Issue by Ana06** [github/pages-gem#555]
Is it plan to update to Jelyll 3.8? Currently 3.7.3 is used. :no_mouth: An update would be great!

**Comment by merlinpatt** [comment]
I would also like to see this. Is there a way to force 3.8 in the meantime?

**Comment by kenman345** [comment]
@merlinpatt Unfortunately, if you're using the github-pages gem then you are locked down. If you were to bring in all these gems themselves instead of github-pages bundling them, then you might be able to get it but its still a bit annoying to have it that way, especially since you wont get those advantages with gh-pages. 

3.8 brings a lot of site generation speed so I hope that PR gets merged soon.

**Comment by merlinpatt** [comment]
@kenman346 I don't know if it will. There was activity a few days ago that was bumping the version of something else, and I would have thought that would be the perfect time to bump Jekyll but it still hasn't happened yet. I don't understand what is holding it up

**Comment by oe** [comment]
@merlinpatt It will, it just takes the (already fairly small) team a lot of time to verify whether the latest version is safe to put on GitHub Pages. There's usually a lot of delay between Jekyll mainline releases and GitHub Pages updates, no need to worry about it.

**Comment by merlinpatt** [comment]
Is there any way the community can help verify that it is safe?

Is there anything we can do to help speed up the process in the future with tests or something?

What are the possible concerns? I thought it was built by GitHub so that should make it easier to handle updates.

What is the usual delay between Jekyll and Pages releases?

Sorry for all the questions, especially if they've already been answered, but I only started using Jekyll/Pages this last year so I don't know about any of this. It would be ideal if there was an FAQ for all this because I'm sure I'm not the only one who's had these questions. 

And from the outside, waiting 4 months for an update, especially without comment from maintainers when there has been other activity on the repo in the meantime, can make it seem like no one cares about this happening.

**Comment by oe** [comment]
@merlinpatt Jekyll and GitHub Pages are developed independently from another. Jekyll has a different release schedule from GitHub Pages, and doesn't try to adjust its to GitHub Pages'. I can't speak for the GitHub Pages team, but from my assumption, GitHub Pages is simply a very large website hosting service, which is why the software it uses needs to be verified secure to be running in a sandboxed environment.

I do agree that there could be more consistency as to _why_ GitHub Pages updates are taking a while. @benbalter has anything like this ever been in the pipeline?

**Comment by JosueDanielBust** [comment]
Any update here?
I get this error today after launch a new update on one site.

> 1 jekyll vulnerability found in Gemfile.lock 2 hours ago
> **Remediation**
> Upgrade **jekyll** to version **3.8.4** or later. For example:
> `gem "jekyll", ">= 3.8.4"`

Details: [CVE-2018-17567](https://nvd.nist.gov/vuln/detail/CVE-2018-17567)

**Comment by marco-c** [comment]
@JosueDanielBust you can fork the repo and set the dependency to your repo, this way you can manually update the version. It's not great as you will have to remember to set it back to the default "github-pages" when the time comes, but better than being stuck on an old version if you really need the update.

**Comment by Ana06** [comment]
@marco-c

> @JosueDanielBust you can fork the repo and set the dependency to your repo, this way you can manually update the version. It's not great as you will have to remember to set it back to the default "github-pages" when the time comes, but better than being stuck on an old version if you really need the update.

But if you host your page in GitHub pages and you require a dependency that is not installed there it won't work

**Comment by merlinpatt** [comment]
It's been 10 months since this issue was first made. What progress has there been?

**Comment by merlinpatt** [comment]
I would like to add that previous releases of Jekyll have been added into the gh-pages gem within weeks, as seen in the chart below. I am very confused why this release has taken nearly a year.

| Version | Jekyll Released | pages-gem updates | Timeframe |
| --- | --- | --- | --- |
| 3.7.3 | 2018-02-25 | 2018-03-16 | < 3 weeks |
| 3.7.2 | 2018-01-25 | 2018-02-05 | < 2 weeks |
| 3.6.2 | 2017-10-21 | 2018-10-23 | < 1 week |
| 3.6.0 | 2017-09-21 | 2017-09-21 | < 1 day |
| 3.6.0.pre.beta1 | 2017-08-23 | 2017-08-24 | < 2 days |

**Comment by dergigi** [comment]
That's strange indeed. I am eagerly awaiting an update as well, so thank you for pushing this issue @merlinpatt

**Comment by BerkhanBerkdemir** [comment]
The funny thing is that there is no comment from a member

**Comment by dergigi** [comment]
Yay, finally! Thanks to however pushed this through 👍

**Comment by brando90** [comment]
I am getting this weird error:

```
$ bundle
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
You have requested:
  jekyll ~> 3.8.5

The bundle currently has jekyll locked at 4.0.0.
Try running `bundle update jekyll`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
```

is there a way to solve it using the solutions discussed here?
