### ISSUE TITLE
Support effective caching using git SHA of the file as HTTP ETag value

### ISSUE THREAD

**Issue by rafalkrupinski** [github/pages-gem#784]
I know this isn't the right repo for this feature request. Please direct me to the right place. Cheers

**Comment by parkr** [comment]
One thing I do on some of my sites is add `?v={{ site.github.build_version }}` which adds the git SHA to the path of a file. This is really helpful for CSS and JS where the file names don't generally change. Not sure if this would help in your case, since it's not an ETag.

Anyway, you can submit this request directly to GitHub via support@github.com or on the GitHub.community website.
